interface Employee {
  firstName: string;
  lastName: string;
  email: string;
  typeTransaction: string;
  transactionAmount: number;
  transactionDate: string;
  signatureCatchPhrase: string;
  commissionAmount: number;
}

export const data: Employee[] = [
  {
    firstName: 'Dusty',
    lastName: 'Kuvalis',
    email: 'Randy63@yahoo.com',
    typeTransaction: 'domestic',
    transactionAmount: 52729,
    transactionDate: '3/20/2023',
    signatureCatchPhrase: 'Cross-platform disintermediate workforce',
    commissionAmount: 2636,
  },
  {
    firstName: "D'angelo",
    lastName: 'Moen',
    email: 'Andrew88@hotmail.com',
    typeTransaction: 'international',
    transactionAmount: 71964,
    transactionDate: '3/9/2023',
    signatureCatchPhrase: 'Virtual local support',
    commissionAmount: 3598,
  },
  {
    firstName: 'Devan',
    lastName: 'Reinger',
    email: 'Melissa_Lockman@hotmail.com',
    typeTransaction: 'international',
    transactionAmount: 72551,
    transactionDate: '8/12/2023',
    signatureCatchPhrase: 'Pre-emptive composite hierarchy',
    commissionAmount: 3628,
  },
  {
    firstName: 'Leonardo',
    lastName: 'Langworth',
    email: 'Chadrick.Goldner87@gmail.com',
    typeTransaction: 'international',
    transactionAmount: 57801,
    transactionDate: '7/25/2023',
    signatureCatchPhrase: 'Progressive real-time core',
    commissionAmount: 2890,
  },
  {
    firstName: 'Douglas',
    lastName: 'Denesik',
    email: 'Dante.Deckow@hotmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 23792,
    transactionDate: '4/12/2023',
    signatureCatchPhrase: 'Operative well-modulated info-mediaries',
    commissionAmount: 1190,
  },
  {
    firstName: 'Jameson',
    lastName: 'Mayer',
    email: 'Rosamond_Schuster@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 80916,
    transactionDate: '10/30/2023',
    signatureCatchPhrase: 'Front-line intermediate firmware',
    commissionAmount: 4046,
  },
  {
    firstName: 'Madaline',
    lastName: 'Quitzon',
    email: 'Alex_Grimes82@hotmail.com',
    typeTransaction: 'international',
    transactionAmount: 68052,
    transactionDate: '1/17/2023',
    signatureCatchPhrase: 'Right-sized high-level algorithm',
    commissionAmount: 3403,
  },
  {
    firstName: 'Wilfrid',
    lastName: 'Vandervort',
    email: 'Buddy.Torphy@gmail.com',
    typeTransaction: 'international',
    transactionAmount: 85573,
    transactionDate: '8/4/2023',
    signatureCatchPhrase: 'Focused interactive secured line',
    commissionAmount: 4279,
  },
  {
    firstName: 'Chelsie',
    lastName: 'Mraz',
    email: 'Ladarius_Thiel70@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 51062,
    transactionDate: '1/6/2021',
    signatureCatchPhrase: 'Diverse attitude-oriented migration',
    commissionAmount: 2553,
  },
  {
    firstName: 'Hassie',
    lastName: 'Bruen',
    email: 'Clair76@gmail.com',
    typeTransaction: 'international',
    transactionAmount: 61196,
    transactionDate: '4/28/2022',
    signatureCatchPhrase: 'Upgradable composite methodology',
    commissionAmount: 3060,
  },
  {
    firstName: 'Daisy',
    lastName: 'Hane',
    email: 'Alverta7@hotmail.com',
    typeTransaction: 'international',
    transactionAmount: 25394,
    transactionDate: '3/2/2023',
    signatureCatchPhrase: 'Exclusive next generation initiative',
    commissionAmount: 1270,
  },
  {
    firstName: 'Wilbert',
    lastName: 'Monahan',
    email: 'Cydney.Jakubowski9@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 79355,
    transactionDate: '4/5/2023',
    signatureCatchPhrase: 'Total asynchronous strategy',
    commissionAmount: 3968,
  },
  {
    firstName: 'Heloise',
    lastName: 'Purdy',
    email: 'Celestino.Kassulke@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 109257,
    transactionDate: '12/23/2023',
    signatureCatchPhrase: 'User-friendly tertiary service-desk',
    commissionAmount: 5463,
  },
  {
    firstName: 'Moises',
    lastName: 'McClure',
    email: 'Arturo29@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 155037,
    transactionDate: '9/23/2023',
    signatureCatchPhrase: 'Public-key exuding complexity',
    commissionAmount: 7752,
  },
  {
    firstName: 'Rahsaan',
    lastName: 'Bauch',
    email: 'Angelita39@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 158595,
    transactionDate: '3/31/2022',
    signatureCatchPhrase: 'Decentralized 6th generation archive',
    commissionAmount: 7930,
  },
  {
    firstName: 'Lorenzo',
    lastName: 'Moore',
    email: 'Emma_Becker33@yahoo.com',
    typeTransaction: 'domestic',
    transactionAmount: 73983,
    transactionDate: '8/22/2023',
    signatureCatchPhrase: 'Reactive fresh-thinking local area network',
    commissionAmount: 3699,
  },
  {
    firstName: 'Richard',
    lastName: 'Bartoletti',
    email: 'Hayden84@gmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 169001,
    transactionDate: '10/13/2023',
    signatureCatchPhrase: 'Streamlined logistical access',
    commissionAmount: 8450,
  },
  {
    firstName: 'Ulises',
    lastName: 'Beatty',
    email: 'Jessie_Kirlin39@yahoo.com',
    typeTransaction: 'domestic',
    transactionAmount: 92008,
    transactionDate: '10/17/2023',
    signatureCatchPhrase: 'Monitored object-oriented interface',
    commissionAmount: 4600,
  },
  {
    firstName: 'Hattie',
    lastName: 'Stehr',
    email: 'Betty78@hotmail.com',
    typeTransaction: 'international',
    transactionAmount: 120554,
    transactionDate: '12/17/2023',
    signatureCatchPhrase: 'Organic bi-directional groupware',
    commissionAmount: 6028,
  },
  {
    firstName: 'Kane',
    lastName: 'Marquardt',
    email: 'Myron.Schaefer45@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 95231,
    transactionDate: '2/28/2023',
    signatureCatchPhrase: 'Stand-alone holistic strategy',
    commissionAmount: 4762,
  },
  {
    firstName: 'Brittany',
    lastName: 'Legros',
    email: 'Rachelle44@yahoo.com',
    typeTransaction: 'domestic',
    transactionAmount: 40908,
    transactionDate: '7/27/2022',
    signatureCatchPhrase: 'Reactive multi-tasking internet solution',
    commissionAmount: 2045,
  },
  {
    firstName: 'Joana',
    lastName: 'Witting',
    email: 'Elyssa.Wiegand@hotmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 136966,
    transactionDate: '8/22/2023',
    signatureCatchPhrase: 'Extended asynchronous moderator',
    commissionAmount: 6848,
  },
  {
    firstName: 'Marshall',
    lastName: 'Gottlieb',
    email: 'Myron53@gmail.com',
    typeTransaction: 'international',
    transactionAmount: 155176,
    transactionDate: '12/25/2023',
    signatureCatchPhrase: 'Business-focused bifurcated access',
    commissionAmount: 7759,
  },
  {
    firstName: 'Nolan',
    lastName: 'Abbott',
    email: 'Sigurd.Murazik17@yahoo.com',
    typeTransaction: 'domestic',
    transactionAmount: 161534,
    transactionDate: '8/3/2021',
    signatureCatchPhrase: 'Robust bifurcated initiative',
    commissionAmount: 8077,
  },
  {
    firstName: 'Guadalupe',
    lastName: 'Goyette',
    email: 'Derek.Senger15@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 20297,
    transactionDate: '6/17/2023',
    signatureCatchPhrase: 'Networked tangible definition',
    commissionAmount: 1015,
  },
  {
    firstName: 'Frankie',
    lastName: 'Balistreri',
    email: 'Gladyce85@gmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 57549,
    transactionDate: '3/16/2021',
    signatureCatchPhrase: 'Diverse 24/7 open system',
    commissionAmount: 2877,
  },
  {
    firstName: 'Jimmie',
    lastName: 'Altenwerth',
    email: 'Kaya37@hotmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 90316,
    transactionDate: '9/1/2022',
    signatureCatchPhrase: 'Decentralized 5th generation functionalities',
    commissionAmount: 4516,
  },
  {
    firstName: 'Ryder',
    lastName: "O'Hara",
    email: 'Korey_Mueller@gmail.com',
    typeTransaction: 'international',
    transactionAmount: 111388,
    transactionDate: '5/8/2021',
    signatureCatchPhrase: 'Multi-layered didactic firmware',
    commissionAmount: 5569,
  },
  {
    firstName: 'Nolan',
    lastName: 'Mayer',
    email: 'Remington.DAmore63@hotmail.com',
    typeTransaction: 'international',
    transactionAmount: 46528,
    transactionDate: '2/21/2023',
    signatureCatchPhrase: 'Open-source stable encoding',
    commissionAmount: 2326,
  },
  {
    firstName: 'Ashley',
    lastName: 'Wolf',
    email: 'Polly_Parker@gmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 132645,
    transactionDate: '9/25/2022',
    signatureCatchPhrase: 'Open-architected well-modulated data-warehouse',
    commissionAmount: 6632,
  },
  {
    firstName: 'Florida',
    lastName: 'Kiehn',
    email: 'Wilhelm_Deckow93@hotmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 65835,
    transactionDate: '8/9/2022',
    signatureCatchPhrase: 'Ameliorated upward-trending benchmark',
    commissionAmount: 3292,
  },
  {
    firstName: 'Monica',
    lastName: 'Crooks',
    email: 'Sabina_Kerluke36@hotmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 70473,
    transactionDate: '3/27/2022',
    signatureCatchPhrase: 'Monitored context-sensitive frame',
    commissionAmount: 3524,
  },
  {
    firstName: 'Callie',
    lastName: 'Kub',
    email: 'Theo.Jakubowski57@hotmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 50844,
    transactionDate: '8/19/2022',
    signatureCatchPhrase: 'Stand-alone stable moderator',
    commissionAmount: 2542,
  },
  {
    firstName: 'Wellington',
    lastName: 'Treutel',
    email: 'Gail54@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 37238,
    transactionDate: '3/22/2023',
    signatureCatchPhrase: 'Innovative background capability',
    commissionAmount: 1862,
  },
  {
    firstName: 'Ethyl',
    lastName: 'Rempel',
    email: 'Joseph_Schoen96@yahoo.com',
    typeTransaction: 'international',
    transactionAmount: 139956,
    transactionDate: '8/17/2022',
    signatureCatchPhrase: 'Function-based analyzing hardware',
    commissionAmount: 6998,
  },
  {
    firstName: 'Lora',
    lastName: 'Harvey',
    email: 'Jeanne25@yahoo.com',
    typeTransaction: 'domestic',
    transactionAmount: 49911,
    transactionDate: '10/7/2021',
    signatureCatchPhrase: 'Reactive 24/7 monitoring',
    commissionAmount: 2496,
  },
  {
    firstName: 'Dock',
    lastName: 'Rolfson',
    email: 'Toney.Jenkins@hotmail.com',
    typeTransaction: 'domestic',
    transactionAmount: 161196,
    transactionDate: '11/8/2023',
    signatureCatchPhrase: 'Cross-group reciprocal knowledge base',
    commissionAmount: 8060,
  },
  {
    firstName: 'Loma',
    lastName: 'Dach',
    email: 'Loma.Jenkins@hotmail.com',
    typeTransaction: 'International',
    transactionAmount: 165993,
    transactionDate: '3/8/2023',
    signatureCatchPhrase: 'Robust 3rd generation capacity',
    commissionAmount: 8300,
  },
  {
    firstName: 'Anibal',
    lastName: 'Ruecker',
    email: 'Anibal.Jenkins@hotmail.com',
    typeTransaction: 'International',
    transactionAmount: 112371,
    transactionDate: '5/26/2022',
    signatureCatchPhrase: 'Sharable 24 hour info-mediaries',
    commissionAmount: 5619,
  },
];
